# Generated by Django 5.1.7 on 2025-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('nome_equipamento', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('sub_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('data_registo', models.DateField(auto_now_add=True)),
                ('sala_arrumacao', models.CharField(max_length=50)),
                ('armario', models.CharField(max_length=50)),
                ('gaveta', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacao_aberta', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('baixa', 'Baixa')], default='ativo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_componentes/')),
            ],
        ),
    ]
