# Generated by Django 5.1.7 on 2025-03-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cabinet_room_alter_component_armario_cabinet_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='armario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.cabinet'),
        ),
        migrations.AlterField(
            model_name='component',
            name='sala_arrumacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.room'),
        ),
    ]
